import React from 'react';
import '../style/styling.css'

function ProgramsScholarships (){
    return (
        <div className='page'>
            <p>List of programs and scholarships students can apply for. These links are listed in the order of their receptiveness and my familiarity with the programs.</p>
            <br/>
            <p><a href="https://windle.org.uk/undergraduate-scholarships-sudan">Windle Trust International</a></p>
            <p>This organization offers a scholarship called Undergraduate Scholarship in Sudan. They focus on refugees, asylum seekers, internally displaced, marginalised and conflict-affected communities in Sudan. They tend to prioritize women. Email Asim Turkawi for application details at <a className="unstyled-link" href="mailto:asim@windle.org.uk">asim@windle.org.uk</a></p>
            <p>I highly recommend that you read the eligibility criteria before you email Turkawi. For students, who were part of the workshop, you still have remaining tuition you need to pay. If you don’t have the means to pay for them, apply to this scholarship as soons as possible. </p>
            <p><a href="https://www.sd.uwc.org/how-to-apply/how-to-apply">UWC</a></p>
            <p>United World Colleges (UWC) is a network of 18 schools in 4 continents. They aim to make “education a force to unite people, nations and cultures for peace and a sustainable future.” For this reason, students from all over the world matriculate in these schools and it is a great IB program to broaden your horizons. If you are interested in an International Baccalaureate diploma, I highly recommend that you apply. This program is for students, who are 15, 16 or 17 years old. For students residing in Sudan, search “UWCSudan” and visit their website. On the left corner, click on “How to apply” and scroll all the way down. You will find two forms, one in Arabic and one in English. Choose whatever language you are most comfortable in and click one of the forms. This form is the application to UWC. </p>
            <p>An example of an application from 2020 is linked here. The first page informs you what you need to complete before you send your application. I briefly talk about UWC in the “Interview Video”. It is very important that you don’t miss the deadline.</p>
            <p>Follow their <a className="unstyled-link" href="https://www.instagram.com/uwcsudan/?hl=en">instagram account</a> for accurate updates.</p>
            {/* <a href="https://www.sd.uwc.org/attachments/download.asp?file=5728&type=pdf">https://www.sd.uwc.org/attachments/download.asp?file=5728&type=pdf</a> */}
            <p><a href="https://www.africanleadershipacademy.org/apply/admission-criteria">African Leadership Academy (ALA)</a></p>
            <p>African Leadership Academy is a secondary school in South Africa similar to UWC. It is a competitive program dedicated to 15 to 18-years-olds students. ALA believes “transformation lies in the hands and minds of young people with a desire to move the continent toward peace and prosperity.” If you have a similar focus, I highly recommend that you apply. Visit their website to read elibiligibily criteria. Students from more financially disadvantaged backgrounds receive financial aid from ALA upon acceptance. Applications open around July.</p>
            <p><a href="https://www.collegeessayguy.com">College Essay Guy</a></p>
            <p>Ethan Sawyer supports students to tell their stories effectively by providing blogs, workshops, podcasts and courses. He has a section on his website that focuses on international students (which is you). The best part is most of the resources are free. </p>
            <p><a href="https://educationusa.state.gov/centers/educationusa-sudan">EducationUSA Sudan</a></p>
            <p>This center provides an educational adviser, a reference library, educational software and sessions. They also provide study materials for admission tests such as TOEFL, GMAT, GRE, SAT, ACT, LSAT and USMLE. You can use their books if you visit their center. Educational advisors provide guidance to propesective international students in terms of selecting appropriate universities, locating financial aid and applying for admission. As of yet, we do not think they charge for this service. To clarify, they do not provide scholarships or opportunities. They connect students to other opportunities. Some of the students in the workshop sent a handwritten essay response. It is possible they might have software you can use if you visit their center. Send them an email if you want to visit their center at <a className="unstyled-link" href="mailto:educationUSAsudan@state.gov">educationUSAsudan@state.gov</a> or use the link below to visit their website.</p>
            <h2 style={{paddingLeft: "6rem"}}>Duolingo </h2>
            <p>Duolingo is an American language-learning resource providing lessons on more than 30 languages. They have a website and an app (download the app for easy access). Some students mentioned they are learning French. This could be an additional great resource. </p>
            <p>Additionally, Duolingo offers an <a className="unstyled-link" href="https://englishtest.duolingo.com/home">English language test</a>, which you can use as a proof of proficiency. The exam fee is $49. However, they recently partnered with UNHCR and IRC to waive this fee for refugees. I recommend that you inform your school about this opportunity. They can request for funds directly since most Eritrean refugee schools are supported by UNHCR. <a className="unstyled-link" href="https://englishtest.duolingo.com/access">Here is the link for the application.</a>Here is the link for the application.</p>
            <p><a className="unstyled-link" href="https://www.ets.org/toefl">Test of English as a Foreign Language (TOEFL)</a> also offers an English standardized test to measure your English proficiency, but the cost for the exam is close to $200. </p>
            <p><a href="https://www.instagram.com/eritreanmuslimscouncil/?hl=en">Eritrean Muslim Council </a></p>
            <p>EMC is a nonprofit organization empowering Eritrean muslims to reach their full potential. Recently, they offered Hummed Neberai Scholarship for Eritrean students admitted to universities in Asia or Africa. Follow their instagram so that such an opportunity doesn’t pass by you in the future.</p>
            <p><a href="https://hub.africanscholarshiphub.org">Education Sub Saharan Africa (ESSA)</a></p>
            <p>This website is a database that can connect you to opportunities in European and African countries. They target students living in Sub Saharan Africa (you qualify for it). Use the website link down below to fill out your interests. First, they ask your preferences. Second, they ask you for information about yourself. It takes 5 minutes to complete it. Then, they will present you with a list of opportunities. This database is useful for students, who recently completed their baccalaureate degrees and want to continue their studies in a master’s or PhD program. </p>
            <p><a href="https://igad.int/igad-schorlarship-information">Intergovernmental Authority on Development (IGAD)</a></p>
            <p>IGAD provides scholarships for East African students particularly refugees, returnees and host communities. “The IGAD scholarship programme is purposefully designed to provide scholarships, prizes, stipends and awards to secondary/high school and tertiary institutions students enrolled in institutions in IGAD as well as professionals working in research and training institutions pursuing postgraduate training.” Preference is given to students under the age of 20.</p>
            <p><a href="https://www.opportunitiesforafricans.com">Opportunities for Africans (OFA)</a></p>
            <p>This website is also another database of opportunities, scholarships, fellowships and internships  for all Africans, who are currently residing in Africa. On the search bar, search “East Africans” or “North Africans” to filter out opportunities you do not qualify for. Once you find an opportunity that sounds interesting, thoroughly check if you qualify for it. This database is useful for students, who recently completed their baccalaureate degrees and want to continue their studies in a master’s or PhD program. </p>
            <h2 style={{paddingLeft: "6rem"}}>Library Genesis</h2>
            <p>Library Genesis is a library website that offers free academic and recreational books. Download the app for easy access. </p>
            <span className="break-line"/>
            <p>If you are a recently resettled Eritrean youth in the US, I direct you to other organizations, who will be more of help. </p>
            <p><a href="https://www.seretfoundation.org">Seret Foundation</a></p>
            <p><a href="https://eritreandiaspora.org">Eritrean Diaspora Network</a></p>
            <p>Eritrean Diaspora Network also has an <a className="unstyled-link" href="https://www.instagram.com/eridiaspora/?hl=en">instagram account</a>.</p>
        </div>
    );
}

export default ProgramsScholarships;